[Main]
name   = "(draft) The Dark Arts"
mode   = "dark"
author = "Myian"

[Base]
base    = "#211d24"
default = "#ddcac1"
faded   = "#6c616e"
red     = "#da7676"
orange  = "#f09870"
yellow  = "#ebc089"
green   = "#7aa079"
cyan    = "#76b49f"
blue    = "#7195ad"
purple  = "#9b77bd"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "default"
inactive = "faded"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "yellow"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "yellow"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "yellow"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#342f38"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "base:L125"
buttonText      = "default"
brightText      = "base"
highlight       = "#4e476b"
highlightedText = "default"
link            = "blue"
linkVisited     = "blue"
accent          = "#49376e"

[GUI]
helpText     = "faded:L125"
fadedText    = "faded"
errorText    = "red"
accentText   = "red"
activeButton  = "#462392"
searchMatch  = "yellow:80"

[Syntax]
background     = "#18151b"
text           = "default"
line           = "#29263c"
link           = "blue"
headerText     = "#948abb"
headerTag      = "#4e476b"
emphasis       = "green"
whitespace     = "purple:64"
dialog         = "#aa7f91"
altDialog      = "green"
note           = "yellow"
hidden         = "faded"
shortcode      = "yellow"
keyword        = "#b65252"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "yellow"
modifier       = "#a37941"
textHighlight  = "#3c3958"

#68445a
#2a495e
#49376e
#201a26
#0e0c11