[Main]
name   = "(draft) Eclipse"
mode   = "dark"
author = "Myian"

[Base]
base    = "#212a3d"
default = "#e6eaf1"
faded   = "#a8b2c7"
red     = "#fa8ea0"
orange  = "#e2ac97"
yellow  = "#f5e4c0"
green   = "#8ae99a"
cyan    = "#a5e6d0"
blue    = "#7aacdb"
purple  = "#c197f0"

[Project]
root     = "default"
folder   = "orange"
file     = "default"
title    = "red"
chapter  = "green"
scene    = "blue"
note     = "yellow"
active   = "cyan"
inactive = "orange"
disabled = "#95a0b6"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "default"
altaction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "#e6acd8"
markdown  = "default"
systemio  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#171f30"
windowText      = "default"
base            = "#171f30"
alternateBase   = "#2f3950"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base:D175"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#e2cea2"
highlightedText = "base:D175"
link            = "red"
linkVisited     = "red"
accent          = "#ce9ac3"

[GUI]
helpText   = "faded"
fadedText  = "faded"
errorText  = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#21202e"
link           = "orange"
headerText     = "blue"
headerTag      = "blue:128"
emphasis       = "blue"
whitespace     = "purple:100"
dialog         = "green"
altDialog      = "orange"
note           = "yellow"
hidden         = "faded"
shortcode      = "#e6acd8"
keyword        = "red"
tag            = "yellow"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorline      = "green"
replaceTag     = "yellow"
modifier       = "purple"
textHighlight  = "#717a8d"
