[Main]
name   = "(draft) Midway Bright"
mode   = "light"
author = "Myian"

[Base]
base    = "#acb3c5"
default = "#2b3249"
faded   = "#5f6b80"
red     = "#974358"
orange  = "#aa5f3c"
yellow  = "#8d6f1d"
green   = "#186d10 "
cyan    = "#167880"
blue    = "#296396"
purple  = "#754999"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "red"
chapter  = "green"
scene    = "blue"
note     = "#69758a"
active   = "cyan"
inactive = "orange"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "default"
altaction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "#8a497d"
markdown  = "default"
systemio  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowtext      = "#1f2a3b"
base            = "base"
alternatebase   = "#959eb4"
text            = "default"
tooltipbase     = "#c9bfac"
tooltiptext     = "default"
button          = "#a8b0c4"
buttontext      = "default"
brighttext      = "base"
highlight       = "#4679a5"
highlightedtext = "#c5cbdb"
link            = "blue"
linkvisited     = "blue"
accent          = "#4679a5"

[GUI]
helpText   = "#444f61"
fadedText  = "faded"
errorText  = "red"

[Syntax]
background     = "#bbc2d3"
text           = "default"
line           = "#21202e"
link           = "blue"
headertext     = "blue"
headertag      = "blue:128"
emphasis       = "blue"
whitespace     = "purple:100"
dialog         = "green"
altdialog      = "orange"
note           = "#836512"
hidden         = "faded"
shortcode      = "#8b5078"
keyword        = "purple"
tag            = "#836512"
value          = "faded"
optional       = "faded"
spellcheckline = "red"
errorline      = "green"
replacetag     = "#836512"
modifier       = "red"
texthighlight  = "#a3abc0"

