[Main]
name   = "(draft) Spring Season"
mode   = "light"
author = "Myian"

[Base]
base    = "#dcecd7"
default = "#43754e"
faded   = "#beb0b9"
red     = "#ee7a7a"
orange  = "#d37c59"
yellow  = "#caa24a"
green   = "#57af54"
cyan    = "#43b4b8"
blue    = "#6299ca"
purple  = "#db85a6"

[Project]
root     = "default"
folder   = "yellow"
file     = "#6b6277"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "#6b6277"
inactive = "faded"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "yellow"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "yellow"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "yellow"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#b0d4a4"
text            = "default"
tooltipBase     = "#ffecad"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#eea9c38e"
highlightedText = "#57524c"
link            = "blue"
linkVisited     = "blue"
accent          = "#eea9c3"

[GUI]
helpText     = "faded:D125"
fadedText    = "faded"
errorText    = "red"
accentText   = "default"
activeButton= "purple:128"
searchMatch  = "yellow:80"

[Syntax]
background     = "#eef7ec"
text           = "#666666"
line           = "#e1dae2"
link           = "blue"
headerText     = "#c5965d"
headerTag      = "#eecfa9"
emphasis       = "purple"
whitespace     = "purple:64"
dialog         = "green"
altDialog      = "blue"
note           = "#7c9fc0"
hidden         = "faded"
shortcode      = "yellow"
keyword        = "#c04d5c"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "green"
modifier       = "#5f76a8"
textHighlight  = "#c5bfca"
