[Main]
name   = "(draft) Midway Dark"
mode   = "dark"
author = "Myian"

[Base]
base    = "#555f75"
default = "#e6eaf1"
faded   = "#a8b2c7"
red     = "#eb9ba9"
orange  = "#e2ac97"
yellow  = "#e2cea2"
green   = "#98d4aa"
cyan    = "#93ced6"
blue    = "#91bee7"
purple  = "#c3a5e6"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "red"
chapter  = "green"
scene    = "blue"
note     = "faded"
active   = "cyan"
inactive = "orange"
disabled = "#95a0b6"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "default"
altaction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "#e6acd8"
markdown  = "default"
systemio  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#747d91"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base:D175"
button          = "#444e64"
buttonText      = "default"
brightText      = "base"
highlight       = "#8bb5dd"
highlightedText = "base:D175"
link            = "red"
linkVisited     = "red"
accent          = "#8bb5dd"

[GUI]
helpText   = "faded"
fadedText  = "faded"
errorText  = "red"

[Syntax]
background     = "#4c5569"
text           = "default"
line           = "#21202e"
link           = "blue"
headerText     = "blue"
headerTag      = "blue:128"
emphasis       = "blue"
whitespace     = "purple:100"
dialog         = "green"
altDialog      = "orange"
note           = "yellow"
hidden         = "faded"
shortcode      = "#e6acd8"
keyword        = "purple"
tag            = "yellow"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorline      = "green"
replaceTag     = "yellow"
modifier       = "red"
textHighlight  = "#747d91"
