[Main]
name   = (draft) Sunshine
mode   = light
author = Myian

[Base]
base    = #f0dbae
default = #313541
faded   = #545f72
red     = #974358
orange  = #aa5f3c
yellow  = #967828
green   = #186d10 
cyan    = #167880
blue    = #235d94
purple  = #754999

[Project]
root     = default
folder   = orange
file     = default
title    = green
chapter  = red
scene    = blue
note     = yellow
active   = cyan
inactive = orange
disabled = faded

[Icon]
tool      = default
sidebar   = default
accept    = green
reject    = red
action    = default
altaction = orange
apply     = green
create    = yellow
destroy   = faded
reset     = green
add       = green
change    = green
remove    = red
shortcode = #8a497d
markdown  = default
systemio  = yellow
info      = blue
warning   = orange
error     = red

[Palette]
window          = base
windowtext      = #1f2a3b
base            = base
alternatebase   = #959eb4
text            = default
tooltipbase     = base
tooltiptext     = default
button          = base
buttontext      = default
brighttext      = base
highlight       = #4e829c
highlightedtext = #f5efe0
link            = blue
linkvisited     = blue
accent          = #96698d

[GUI]
helptext  = #444f61
fadedtext = faded
errortext = red

[Syntax]
background     = #f5e9cc
text           = default
line           = #21202e
link           = #8b5078
headertext     = blue
headertag      = blue:128
emphasis       = blue
whitespace     = purple:100
dialog         = green
altdialog      = orange
note           = #836512
hidden         = faded
shortcode      = #8b5078
keyword        = red
tag            = #836512
value          = faded
optional       = faded
spellcheckline = red
errorline      = green
replacetag     = #836512
modifier       = purple
texthighlight  = #959eb4

