[Main]
name   = (draft) Midway Dark
mode   = dark
author = Myian

[Base]
base    = #555f75
default = #e6eaf1
faded   = #a8b2c7
red     = #eb9ba9
orange  = #e2ac97
yellow  = #e2cea2
green   = #98d4aa
cyan    = #93ced6
blue    = #91bee7
purple  = #c3a5e6

[Project]
root     = default
folder   = yellow
file     = default
title    = red
chapter  = green
scene    = blue
note     = faded
active   = cyan
inactive = orange
disabled = #95a0b6

[Icon]
tool      = default
sidebar   = default
accept    = green
reject    = red
action    = default
altaction = orange
apply     = green
create    = yellow
destroy   = faded
reset     = green
add       = green
change    = green
remove    = red
shortcode = #e6acd8
markdown  = default
systemio  = yellow
info      = blue
warning   = orange
error     = red

[Palette]
window          = base
windowtext      = default
base            = base
alternatebase   = #747d91
text            = default
tooltipbase     = yellow
tooltiptext     = base:D175
button          = #444e64
buttontext      = default
brighttext      = base
highlight       = #8bb5dd
highlightedtext = base:D175
link            = red
linkvisited     = red
accent          = #8bb5dd

[GUI]
helptext  = faded
fadedtext = faded
errortext = red

[Syntax]
background     = #4c5569
text           = default
line           = #21202e
link           = blue
headertext     = blue
headertag      = blue:128
emphasis       = blue
whitespace     = purple:100
dialog         = green
altdialog      = orange
note           = yellow
hidden         = faded
shortcode      = #e6acd8
keyword        = purple
tag            = yellow
value          = faded
optional       = faded
spellcheckline = red
errorline      = green
replacetag     = yellow
modifier       = red
texthighlight  = #747d91
