[Main]
name       = "(draft) Chiaroscuro"
mode       = "dark"
author     = "Myian"

[Base]
base    = "#2c2d32"
default = "#f2f2f5"
faded   = "#7e8692"
red     = "#f2777a"
orange  = "#f99157"
yellow  = "#ffd581"
green   = "#99cc99"
cyan    = "#66cccc"
blue    = "#6699cc"
purple  = "#cc99cc"

[Project]
root     = "default"
folder   = "orange"
file     = "red"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "yellow"
active   = "green"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "#c052c0"
markdown  = "base"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default:D110"
base            = "base"
alternateBase   = "base:L150"
text            = "default:D110"
tooltipBase     = "yellow:L125"
tooltipText     = "base"
button          = "base"
buttonText      = "faded"
brightText      = "base"
highlight       = "blue"
highlightedText = "default:L200"
link            = "blue:L125"
linkVisited     = "blue:L125"
accent          = "blue"

[GUI]
helpText   = "default:D140"
fadedText  = "faded"
errorText  = "red"
accentText   = "#acdeff"
activeButton = "blue:128"
activeBase   = "base:L160"
searchMatch  = "red:96"

[Syntax]
background     = "default"
text           = "base"
line           = "default:D110"
link           = "blue"
headerText     = "#218837"
headerTag      = "#21883780"
emphasis       = "#218837"
whitespace     = "#21883740"
dialog         = "#2068b1"
altDialog      = "#d3682e"
note           = "#d84749"
hidden         = "#6a6a72"
shortcode      = "#c052c0"
keyword        = "#c052c0"
tag            = "#30a1a1"
value          = "#68666b"
optional       = "faded"
spellCheckLine = "#d84749"
errorLine      = "#30a1a1"
replaceTag     = "#d3682e"
modifier       = "#c052c0"
textHighlight  = "blue:128"

#d84749
#30a1a1