[Main]
name       = "(draft) Chiaroscuro"
mode       = "dark"
author     = "Myian"

[Base]
base    = "#26282e"
default = "#c4c4c4"
faded   = "#6e7681"
red     = "#d73f3f"
orange  = "#f56512"
yellow  = "#ffc935"
green   = "#38a13f"
cyan    = "#2fbba4"
blue    = "#3790f5"
purple  = "#ad56ff"

[Project]
root     = "default"
folder   = "orange"
file     = "default"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "yellow"
active   = "green"
inactive = "red"
disabled = "faded"

[Palette]
window          = "base"
windowtext      = "#e2e2e2"
base            = "base"
alternatebase   = "#4a4d57"
text            = "#dddddd"
tooltipbase     = "yellow"
tooltiptext     = "base"
button          = "base"
buttontext      = "#a2a6b6"
brighttext      = "base"
highlight       = "blue"
highlightedtext = "#ffffff"
link            = "blue:L125"
linkvisited     = "blue:L125"
accent          = "blue:D125"

[GUI]
helpText   = "default:192"
fadedText  = "faded"
errorText  = "red"

[Syntax]
background     = "#ffffff"
text           = "#212125"
line           = "#e5e8ec"
link           = "blue"
headertext     = "#1a8d22"
headertag      = "#1a8d2280"
emphasis       = "#1a8d22"
dialog         = "#1d69c0"
altdialog      = "#00947b"
note           = "#df5200"
hidden         = "#6a6a72"
shortcode      = "#df5200"
keyword        = "#c52121"
tag            = "#8e3bdb"
value          = "#68666b"
optional       = "faded"
spellcheckline = "red"
errorline      = "cyan"
replacetag     = "purple"
modifier       = "#c52121"
texthighlight  = "blue:64"
