[Main]
name       = (draft) Jewel Case Dark
mode       = dark
author     = Myian

[Base]
base    = #141a27
default = #bbd0e0
faded   = #56687c
red     = #d47d8c
orange  = #e7a172
yellow  = #eee7aa
green   = #7cc08b
cyan    = #6ac3cf
blue    = #6793e4
purple  = #bc90d6

[Project]
root     = default
folder   = yellow
file     = default
title    = purple
chapter  = #548d60
scene    = green
note     = faded
active   = default
inactive = faded
disabled = #2b374e

[Palette]
window          = base
windowtext      = default
base            = base
alternatebase   = #2d3c57
text            = default
tooltipbase     = yellow
tooltiptext     = base
button          = #131e31
buttontext      = default
brighttext      = base
highlight       = #a85066
highlightedtext = #ffffff
link            = blue
linkvisited     = blue
accent          = #a85066

[GUI]
helptext  = #768da0
fadedtext = faded
errortext = red

[Syntax]
background     = #0f141f
text           = default
line           = base
link           = blue
headertext     = #ffffff
headertag      = faded
emphasis       = green
dialog         = #85aad4
altdialog      = cyan
note           = red
hidden         = faded
shortcode      = #548d60
keyword        = #b3a66e
tag            = #fff8bc
value          = #ffffff
optional       = cyan
spellcheckline = red
errorline      = cyan
replacetag     = red
modifier       = #a85066
texthighlight  = #2d3c57

#keyword        = #9168b3