[Main]
name   = "(draft) Ocean Deep"
mode   = "dark"
author = "Myian"

[Base]
base    = "#1a2434"
default = "#c6e3fa"
faded   = "#8d98a7"
red     = "#ff506d"
orange  = "#ff864a"
yellow  = "#ffd37b"
green   = "#6ace7a"
cyan    = "#5adab3"
blue    = "#63c0eb"
purple  = "#dd85f8"

[Project]
root     = "default"
folder   = "orange"
file     = "default"
title    = "green"
chapter  = "#2e8ebb"
scene    = "blue"
note     = "yellow"
active   = "green"
inactive = "red"
disabled = "faded:D150"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#151c29"
windowText      = "default"
base            = "base"
alternateBase   = "#2f435a"
text            = "default"
tooltipBase     = "#ffffc0"
tooltipText     = "#15150d"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#487091"
highlightedText = "#ffffff"
link            = "blue"
linkVisited     = "blue"
accent          = "#2c98f7"

[GUI]
helpText     = "faded"
fadedText    = "faded"
errorText    = "red"
accentText   = "blue"
activeButton = "blue:128"
activeBase   = "#575757"
searchMatch  = "orange:96"

[Syntax]
background     = "base"
text           = "default"
line           = "default:32"
link           = "blue"
headerText     = "cyan"
headerTag      = "cyan:128"
emphasis       = "cyan"
whitespace     = "orange:64"
dialog         = "blue"
altDialog      = "red"
note           = "yellow"
hidden         = "faded"
shortcode      = "blue"
keyword        = "red"
tag            = "purple"
value          = "faded"
optional       = "blue"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "green"
modifier       = "orange"
textHighlight  = "blue:72"
