[Main]
name   = "(draft) Inkling Negative"
mode   = "dark"
author = "Myian"

[Base]
base    = "#19181a"
default = "#e9ded1"
faded   = "#78757c"
red     = "#f3827a"
orange  = "#f3af90"
yellow  = "#dbc2a5"
green   = "#9ec58e"
cyan    = "#609b72"
blue    = "#748caf"
purple  = "#e99aa5"

[Project]
root     = "default"
folder   = "orange"
file     = "faded"
title    = "default"
chapter  = "yellow"
scene    = "orange"
note     = "blue"
active   = "yellow"
inactive = "faded"
disabled = "#4e4c52"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "yellow"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "faded"
markdown  = "orange"
system    = "blue"
info      = "yellow"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#353436"
text            = "#d3cdc6"
tooltipBase     = "#f0e3d1"
tooltipText     = "base"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#ffd9b590" #"#a7998d"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "#a3836d"

[GUI]
helpText     = "#cab9a3"
fadedText    = "faded"
errorText    = "red"
accentText   = "yellow"
activeButton = "#3f3e41"
activeBase   = "#353436"
searchMatch  = "default:72"

[Syntax]
background     = "#242325"
text           = "default"
line           = "#353436"
link           = "blue"
headerText     = "#e9e6e3"
headerTag      = "yellow"
emphasis       = "orange"
whitespace     = "#96acc260"
dialog         = "yellow"
altDialog      = "#96acc2"
note           = "green"
hidden         = "faded"
shortcode      = "faded"
keyword        = "blue"
tag            = "#96acc2"
value          = "yellow"
optional       = "orange"
spellCheckLine = "#df5858"
errorLine      = "#70ce6d"
replaceTag     = "green"
modifier       = "cyan"
textHighlight  = "#96acc260"
