[Main]
name   = "(draft) Parchment"
mode   = "light"
author = "Myian"

[Base]
base    = "#e9e3d9"
default = "#5f4c42"
faded   = "#9e948d"
red     = "#d85341"
orange  = "#d18241"
yellow  = "#ddb73b"
green   = "#59973c"
cyan    = "#3daa89"
blue    = "#5198b4"
purple  = "#bf8ace"

[Project]
root     = "default"
folder   = "faded"
file     = "faded"
title    = "green"
chapter  = "red"
scene    = "#eb7f77"
note     = "#c99c59"
active   = "#685e59"
inactive = "faded"
disabled = "faded:L125"

#bf8ace
#c99c59

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "#8a7b71"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "purple"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#d6cdc2"
windowText      = "default"
base            = "base"
alternateBase   = "#f4f2ec"
text            = "default"
tooltipBase     = "#ffffc0"
tooltipText     = "#15150d"
button          = "#f4f2ec"
buttonText      = "default"
brightText      = "base"
highlight       = "#f1daad"
highlightedText = "default"
link            = "blue"
linkVisited     = "blue"
accent          = "#ceac86"

[GUI]
helpText     = "#5c5c5c"
fadedText    = "#6c6c6c"
errorText    = "red"
accentText   = "red"
activeButton = "blue:96"
activeBase   = "#f4f2ec"
searchMatch  = "orange:96"

[Syntax]
background     = "#f4f2ec"
text           = "#685e59"
line           = "default:32"
link           = "blue"
headerText     = "default"
headerTag      = "#c2ac93"
emphasis       = "green"
whitespace     = "orange:64"
dialog         = "red"
altDialog      = "red"
note           = "blue"
hidden         = "faded"
shortcode      = "blue"
keyword        = "#9761bb"
tag            = "purple"
value          = "faded"
optional       = "blue"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "green"
modifier       = "#196fa8"
textHighlight  = "yellow:72"
