[Main]
name   = "(draft) Oneline"
mode   = "dark"
author = "Myian"

[Base]
base    = "#161B26"
default = "#ffffff"
faded   = "#a3aabf"
red     = "#e20074"
orange  = "#fa8f66"
yellow  = "#deb457"
green   = "#33cc66"
cyan    = "#00a0de"
blue    = "#688bf2"
purple  = "#d079fc"

[Project]
root     = "default"
folder   = "faded"
file     = "default"
title    = "yellow"
chapter  = "cyan"
scene    = "green"
note     = "red"
active   = "default"
inactive = "faded"
disabled = "#474c59"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "faded"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "green"
markdown  = "default"
system    = "yellow"
info      = "cyan"
warning   = "orange"
error     = "red"

[Palette]
window          = "#090C14"
windowText      = "default"
base            = "base"
alternateBase   = "#474c59"
text            = "default"
tooltipBase     = "#ffffc0"
tooltipText     = "#15150d"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#8fafc5"
highlightedText = "base"
link            = "cyan"
linkVisited     = "cyan"
accent          = "red"

[GUI]
helpText     = "#a4a4a4"
fadedText    = "faded"
errorText    = "red"
accentText   = "cyan"
activeButton = "#474c59"
activeBase   = "base"
searchMatch  = "cyan:96"

[Syntax]
background     = "base"
text           = "faded"
line           = "default:32"
link           = "cyan"
headerText     = "default"
headerTag      = "faded"
emphasis       = "red"
whitespace     = "faded:64"
dialog         = "default"
altDialog      = "red"
note           = "cyan"
hidden         = "#474c59"
shortcode      = "green"
keyword        = "default"
tag            = "red"
value          = "green"
optional       = "green"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "green"
modifier       = "default"
textHighlight  = "red:72"
