[Main]
name   = "(draft) Inkling"
mode   = "light"
author = "Myian"

[Base]
base    = "#e2e1de"
default = "#2d3047"
faded   = "#7e899c"
red     = "#a64253"
orange  = "#c97d3f"
yellow  = "#bea46b"
green   = "#2a4d14"
cyan    = "#2d7c4b"
blue    = "#143f70"
purple  = "#b9628d"

[Project]
root     = "default"
folder   = "orange"
file     = "faded"
title    = "default"
chapter  = "#475c97"
scene    = "#6585c0"
note     = "red"
active   = "default"
inactive = "faded"
disabled = "#b7bfcc"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "faded"
markdown  = "blue"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#c4c2bf"
text            = "default"
tooltipBase     = "#f0e3d1"
tooltipText     = "default"
button          = "#f1f0ec"
buttonText      = "default"
brightText      = "base"
highlight       = "blue:64"
highlightedText = "default"
link            = "blue"
linkVisited     = "blue"
accent          = "blue:96"

[GUI]
helpText     = "#4b5779"
fadedText    = "#6c6c6c"
errorText    = "red"
accentText   = "blue"
activeButton = "blue:48"
activeBase   = "#f1f0ec"
searchMatch  = "blue:48"

[Syntax]
background     = "#f0efec"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "default"
headerTag      = "blue:192"
emphasis       = "#398b96"
whitespace     = "orange:64"
dialog         = "blue"
altDialog      = "#b36f5b"
note           = "cyan"
hidden         = "faded"
shortcode      = "faded"
keyword        = "red"
tag            = "purple"
value          = "#5670b8"
optional       = "orange"
spellCheckLine = "#dd4b63"
errorLine      = "#29a759"
replaceTag     = "green"
modifier       = "green"
textHighlight  = "orange:64"
