[Main]
name   = "(draft) Inkling"
mode   = "light"
author = "Myian"

[Base]
base    = "#e2e1de"
default = "#2d3047"
faded   = "#7e899c"
red     = "#a64253"
orange  = "#c97d3f"
yellow  = "#a19c51"
green   = "#2a4d14"
cyan    = "#2d7c4b"
blue    = "#133d6d"
purple  = "#b34e74"

[Project]
root     = "default"
folder   = "orange"
file     = "faded"
title    = "default"
chapter  = "#4b5779"
scene    = "#6478af"
note     = "red"
active   = "default"
inactive = "faded"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#c4c2bf"
text            = "default"
tooltipBase     = "#ffffc0"
tooltipText     = "#15150d"
button          = "#efefef"
buttonText      = "default"
brightText      = "base"
highlight       = "#adb8c7"
highlightedText = "default"
link            = "blue"
linkVisited     = "blue"
accent          = "#3087c6"

[GUI]
helpText     = "#5c5c5c"
fadedText    = "#6c6c6c"
errorText    = "red"
accentText   = "blue"
activeButton = "blue:96"
activeBase   = "#d7d7d7"
searchMatch  = "orange:96"

[Syntax]
background     = "#f1f0ec"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "default"
headerTag      = "#46668a"
emphasis       = "#398b96"
whitespace     = "orange:64"
dialog         = "blue"
altDialog      = "red"
note           = "cyan"
hidden         = "faded"
shortcode      = "faded"
keyword        = "red"
tag            = "purple"
value          = "#6478af"
optional       = "blue"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "green"
modifier       = "green"
textHighlight  = "yellow:72"
