[Main]
name   = "(draft) Warm"
mode   = "dark"
author = "Myian"

[Base]
base    = "#191a1f"
default = "#f8f8f0"
faded   = "#606f73"
red     = "#ff5846"
orange  = "#f38a4f"
yellow  = "#ffc862"
green   = "#70f39e"
cyan    = "#1abc9c"
blue    = "#84dfeb"
purple  = "#ec91d6"

[Project]
root     = "red"
folder   = "default"
file     = "default"
title    = "green"
chapter  = "cyan"
scene    = "blue"
note     = "yellow"
active   = "default"
inactive = "faded"
disabled = "faded:D150"

[Icon]
tool      = "default"
sidebar   = "red"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "purple"
markdown  = "yellow"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#2e4a53"
text            = "default"
tooltipBase     = "#a9babe"
tooltipText     = "base"
button          = "#21272e"
buttonText      = "default"
brightText      = "base"
highlight       = "#92bac7"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "#60da8a"

[GUI]
helpText     = "#a9babe"
fadedText    = "faded"
errorText    = "red"
accentText   = "blue"
activeButton = "#344758"
activeBase   = "#2d333a"
searchMatch  = "green:96"

[Syntax]
background     = "#21272e"
text           = "default"
line           = "#2e4a53"
link           = "blue"
headerText     = "default"
headerTag      = "red"
emphasis       = "yellow"
whitespace     = "blue:64"
dialog         = "blue"
altDialog      = "red"
note           = "red"
hidden         = "faded"
shortcode      = "purple"
keyword        = "green"
tag            = "red"
value          = "cyan"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "cyan"
modifier       = "green"
textHighlight  = "blue:96"

#9cd230
#53df83
#1abc9c
#56b6c2
#84dfeb