[Main]
name       = (draft) Jewel Case Light
mode       = light
author     = Myian

[Base]
base    = #f6f9fc
default = #2a3744
faded   = #6d7b8b
red     = #be4255
orange  = #bd6e15
yellow  = #8b7a00
green   = #2f7a46
cyan    = #2a9c8f
blue    = #2e6fd1
purple  = #7a4da9

[Project]
root     = default
folder   = orange
file     = default
title    = blue
chapter  = green
scene    = yellow
note     = faded
active   = default
inactive = faded
disabled = #9aa9b9

[Palette]
window          = #e1e7ec
windowtext      = default
base            = base
alternatebase   = #c4d0da
text            = default
tooltipbase     = yellow
tooltiptext     = base
button          = base
buttontext      = default
brighttext      = base
highlight       = #d15b6d
highlightedtext = #ffffff
link            = blue
linkvisited     = blue
accent          = #d15b6d

[GUI]
helptext  = #44505e
fadedtext = faded
errortext = red

[Syntax]
background     = base
text           = default
line           = #e1e7ec
link           = blue
headertext     = #000000
headertag      = faded
emphasis       = yellow
dialog         = green
altdialog      = orange
note           = red
hidden         = faded
shortcode      = #2e6b3f
keyword        = #1e4c93
tag            = blue
value          = #000000
optional       = faded
spellcheckline = red
errorline      = cyan
replacetag     = red
modifier       = #991635
texthighlight  = #c4d0da
