[Main]
name       = "(private) IG"
mode       = "dark"
author     = "Myian"

[Base]
base    = "#272422"
default = "#e9e5df"
faded   = "#9e888d"
red     = "#da8484"
orange  = "#e6ab84"
yellow  = "#ebcd97"
green   = "#aeca9e"
cyan    = "#93ceb7"
blue    = "#97b6cc"
purple  = "#c294be"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "blue"
chapter  = "green"
scene    = "#739461"
note     = "faded"
active   = "default"
inactive = "faded"
disabled = "#5c4c4f"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "default"
altaction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "green"
markdown  = "default"
systemio  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowtext      = "default"
base            = "base"
alternatebase   = "#554d4f"
text            = "default"
tooltipbase     = "#c9b7bb"
tooltiptext     = "base"
button          = "#312d2e"
buttontext      = "default"
brighttext      = "base"
highlight       = "faded"
highlightedtext = "base"
link            = "blue"
linkvisited     = "blue"
accent          = "yellow"

[GUI]
helpText   = "faded"
fadedText  = "faded"
errorText  = "red"

[Syntax]
background     = "#2e2b29"
text           = "default"
line           = "#1d2636"
link           = "blue"
headertext     = "default"
headertag      = "faded"
emphasis       = "blue"
whitespace     = "#554d4f"
dialog         = "green"
altdialog      = "purple"
note           = "faded"
hidden         = "faded"
shortcode      = "#be626a"
keyword        = "#a3669e"
tag            = "faded"
value          = "#ffffff"
optional       = "cyan"
spellcheckline = "red"
errorline      = "green"
replacetag     = "#a3669e"
modifier       = "#be626a"
texthighlight  = "#554d4f"