[Main]
name       = (private) TC
mode       = dark
author     = Myian

[Base]
base    = #182029
default = #e9e5df
faded   = #848683
red     = #b35235
orange  = #c28a55
yellow  = #d1a875
green   = #71964b
cyan    = #699e8e
blue    = #749ab8
purple  = #c294be

[Project]
root     = default
folder   = default
file     = default
title    = purple
chapter  = blue
scene    = green
note     = faded
active   = default
inactive = faded
disabled = base

[Icon]
tool      = default
sidebar   = default
accept    = green
reject    = red
action    = default
altaction = orange
apply     = green
create    = yellow
destroy   = faded
reset     = green
add       = green
change    = green
remove    = red
shortcode = green
markdown  = default
systemio  = yellow
info      = blue
warning   = orange
error     = red

[Palette]
window          = base
windowtext      = default
base            = base
alternatebase   = #31444a
text            = default
tooltipbase     = #c9b7bb
tooltiptext     = base
button          = base
buttontext      = default
brighttext      = base
highlight       = #737d7b
highlightedtext = base
link            = blue
linkvisited     = blue
accent          = #737d7b

[GUI]
helptext  = faded
fadedtext = faded
errortext = red

[Syntax]
background     = base
text           = default
line           = #1d2636
link           = blue
headertext     = default
headertag      = faded
emphasis       = blue
whitespace     = #554d4f
dialog         = green
altdialog      = purple
note           = faded
hidden         = faded
shortcode      = #be626a
keyword        = yellow
tag            = faded
value          = #ffffff
optional       = cyan
spellcheckline = red
errorline      = green
replacetag     = #a3669e
modifier       = red
texthighlight  = #554d4f