[Main]
name       = "(private) NG"
mode       = "dark"
author     = "Myian"

[Base]
base    = "#ffffff"
default = "base:D140"
faded   = "base:D220"
red     = "#ff9b9b"
orange  = "#e7a172"
yellow  = "#d1ba8f"
green   = "#92c09d"
cyan    = "#6acfc7"
blue    = "#8e99cf"
purple  = "#bf9bcf"

[Project]
root     = "default"
folder   = "red"
file     = "default"
title    = "base"
chapter  = "red"
scene    = "#db7676"
note     = "faded"
active   = "base:D120"
inactive = "faded"
disabled = "base:D340"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "default"
altaction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "red"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "blue"
markdown  = "default"
systemio  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base:D540"
windowtext      = "default"
base            = "base:D540"
alternatebase   = "base:D320"
text            = "default"
tooltipbase     = "base:D120"
tooltiptext     = "base:D800"
button          = "base:D540"
buttontext      = "default"
brighttext      = "base"
highlight       = "base:D120"
highlightedtext = "base:D800"
link            = "blue"
linkvisited     = "blue"
accent          = "base:D120"

[GUI]
helptext  = "base:D180"
fadedtext = "faded"
errortext = "red"

[Syntax]
background     = "base:D700"
text           = "default"
line           = "#1d2636"
link           = "blue"
headertext     = "default:L115"
headertag      = "faded"
emphasis       = "red"
whitespace     = "blue:72"
dialog         = "#ffffff"
altdialog      = "green"
note           = "purple"
hidden         = "faded"
shortcode      = "#5a8364"
keyword        = "#6e7ab6"
tag            = "blue"
value          = "#ffffff"
optional       = "cyan"
spellcheckline = "red"
errorline      = "green"
replacetag     = "#5a8364"
modifier       = "#946fa5"
texthighlight  = "base:D360"