[Main]
name       = "(private) NG"
mode       = "dark"
author     = "Myian"

[Base]
base    = "#363636"
default = "#ffffff"
faded   = "default:D200"
red     = "#ff9b9b"
orange  = "#e7a172"
yellow  = "#ddc393"
green   = "#92c09d"
cyan    = "#6acfc7"
blue    = "#99acdf"
purple  = "#bf9bcf"

[Project]
root     = "default"
folder   = "yellow"
file     = "default:D150"
title    = "default"
chapter  = "red"
scene    = "#db7676"
note     = "purple"
active   = "default:D120"
inactive = "faded"
disabled = "default:D300"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "yellow"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default:D110"
base            = "base"
alternateBase   = "base:L150"
text            = "default:D110"
tooltipBase     = "default:D125"
tooltipText     = "base"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "default:128"
highlightedText = "base:D160"
link            = "blue"
linkVisited     = "blue"
accent          = "#964949"

[GUI]
helpText     = "default:D135"
fadedText    = "faded"
errorText    = "red"
accentText   = "default"
activeButton = "base:L150"
activeBase   = "base:L150"
searchMatch  = "purple:64"

[Syntax]
background     = "base:D140"
text           = "default:D125"
line           = "#1d2636"
link           = "blue"
headerText     = "default"
headerTag      = "faded"
emphasis       = "red"
whitespace     = "default:64"
dialog         = "default"
altDialog      = "green"
note           = "yellow"
hidden         = "faded"
shortcode      = "yellow"
keyword        = "purple:176"
tag            = "purple"
value          = "#ffffff"
optional       = "cyan"
spellCheckLine = "red"
errorline      = "green"
replaceTag     = "#926ea1"
modifier       = "yellow:144"
textHighlight  = "red:64"

#5a8364