[Main]
name       = "(private) TC"
mode       = "dark"
author     = "Myian"

[Base]
base    = "#202a33"
default = "#f0e9de"
faded   = "#838281"
red     = "#c25e3f"
orange  = "#c28a55"
yellow  = "#d1a875"
green   = "#75a77b"
cyan    = "#699e8e"
blue    = "#7c9bb4"
purple  = "#b9849e"

[Project]
root     = "default"
folder   = "default"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "faded"
active   = "default"
inactive = "faded"
disabled = "base"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "default"
altaction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "red"
markdown  = "default"
systemio  = "yellow"
info      = "default"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowtext      = "default"
base            = "base"
alternatebase   = "#31424a"
text            = "default"
tooltipbase     = "#aabdb4"
tooltiptext     = "base"
button          = "base"
buttontext      = "default"
brighttext      = "base"
highlight       = "#617473"
highlightedtext = "#182029"
link            = "blue"
linkvisited     = "blue"
accent          = "#87aa99"

[GUI]
helptext  = "#9ea7a3"
fadedtext = "faded"
errortext = "red"

[Syntax]
background     = "#182029"
text           = "default"
line           = "#1d2636"
link           = "blue"
headertext     = "purple"
headertag      = "purple:128"
emphasis       = "blue"
whitespace     = "#2c3738"
dialog         = "green"
altdialog      = "purple"
note           = "faded"
hidden         = "faded"
shortcode      = "red"
keyword        = "yellow"
tag            = "faded"
value          = "yellow"
optional       = "cyan"
spellcheckline = "red"
errorline      = "green"
replacetag     = "#a3669e"
modifier       = "red"
texthighlight  = "#2f4144"