[Main]
name       = (private) HMITD
mode       = dark
author     = Myian

[Base]
base    = #161f31
default = #cdd9e4
faded   = #56687c
red     = #d3828d
orange  = #e7a172
yellow  = #d1ba8f
green   = #92c09d
cyan    = #6acfc7
blue    = #7ca4ca
purple  = #bc90d6

[Project]
root     = default
folder   = red
file     = default
title    = yellow
chapter  = blue
scene    = #506f97
note     = faded
active   = default
inactive = faded
disabled = #2b374e

[Icon]
tool      = default
sidebar   = default
accept    = green
reject    = red
action    = default
altaction = orange
apply     = green
create    = yellow
destroy   = faded
reset     = green
add       = green
change    = green
remove    = red
shortcode = green
markdown  = default
systemio  = yellow
info      = blue
warning   = orange
error     = red

[Palette]
window          = base
windowtext      = default
base            = base
alternatebase   = #2a364d
text            = default
tooltipbase     = yellow
tooltiptext     = base
button          = #161f31
buttontext      = default
brighttext      = base
highlight       = blue
highlightedtext = base
link            = blue
linkvisited     = blue
accent          = yellow

[GUI]
helptext  = #8297ad
fadedtext = faded
errortext = red

[Syntax]
background     = #101829
text           = default
line           = #1d2636
link           = blue
headertext     = #ffffff
headertag      = faded
emphasis       = yellow
whitespace     = blue:72
dialog         = blue
altdialog      = purple
note           = red
hidden         = faded
shortcode      = #548d60
keyword        = #56835f
tag            = green
value          = #ffffff
optional       = cyan
spellcheckline = red
errorline      = green
replacetag     = #a85066
modifier       = #a85066
texthighlight  = #2a364d