[Main]
name       = "(private) IG"
mode       = "dark"
author     = "Myian"

[Base]
base    = "#272422"
default = "#e9e5df"
faded   = "#9e888d"
red     = "#da8484"
orange  = "#e6ab84"
yellow  = "#ebcd97"
green   = "#aeca9e"
cyan    = "#93ceb7"
blue    = "#97b6cc"
purple  = "#c294be"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "blue"
chapter  = "green"
scene    = "#739461"
note     = "faded"
active   = "default"
inactive = "faded"
disabled = "#5c4c4f"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "red"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#554d4f"
text            = "default"
tooltipBase     = "#c9b7bb"
tooltipText     = "base"
button          = "#312d2e"
buttonText      = "default"
brightText      = "base"
highlight       = "faded"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "yellow"

[GUI]
helpText     = "faded"
fadedText    = "faded"
errorText    = "red"
accentText   = "default"
activeButton = "#554d4f"
activeBase   = "#554d4f"
searchMatch  = "#554d4f"

[Syntax]
background     = "#2e2b29"
text           = "default"
line           = "#1d2636"
link           = "blue"
headerText     = "default"
headerTag      = "faded"
emphasis       = "blue"
whitespace     = "#554d4f"
dialog         = "green"
altDialog      = "purple"
note           = "faded"
hidden         = "faded"
shortcode      = "#be626a"
keyword        = "#a3669e"
tag            = "faded"
value          = "#ffffff"
optional       = "cyan"
spellCheckLine = "red"
errorline      = "green"
replaceTag     = "#a3669e"
modifier       = "#be626a"
textHighlight  = "#554d4f"