[Main]
name       = (private) Esc
mode       = dark
author     = Myian

[Base]
base    = #23242b
default = #e9e7df
faded   = #9298a1
red     = #ec7272
orange  = #ec8e57
yellow  = #ffde74
green   = #81be86
cyan    = #67cac0
blue    = #70a7d4
purple  = #c79ddf

[Project]
root     = default
folder   = yellow
file     = default
title    = red
chapter  = blue
scene    = green
note     = faded
active   = default
inactive = faded
disabled = #4e545e

[Palette]
window          = base
windowtext      = default
base            = base
alternatebase   = #474855
text            = default
tooltipbase     = yellow
tooltiptext     = base
button          = #262931
buttontext      = default
brighttext      = base
highlight       = #455d8a
highlightedtext = default
link            = blue
linkvisited     = blue
accent          = #455d8a

[GUI]
helptext  = default:192
fadedtext = faded
errortext = red

[Syntax]
background     = #1b1c22
text           = faded
line           = #1b1c22
link           = blue
headertext     = yellow
headertag      = yellow:128
emphasis       = yellow
dialog         = default
altdialog      = orange
note           = red
hidden         = #545d6b
shortcode      = green
keyword        = green
tag            = blue
value          = blue
optional       = faded
spellcheckline = red
errorline      = cyan
replacetag     = blue
modifier       = green
texthighlight  = #545d6b80
