[Main]
name       = "(private) Esc"
mode       = "dark"
author     = "Myian"

[Base]
base    = "#191f2c"
default = "#dfe5e9"
faded   = "#56687c"
red     = "#ec7272"
orange  = "#ec8e57"
yellow  = "#ffe283"
green   = "#81be86"
cyan    = "#67cac0"
blue    = "#70a7d4"
purple  = "#c79ddf"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "red"
chapter  = "blue"
scene    = "green"
note     = "faded"
active   = "default"
inactive = "faded"
disabled = "base"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altaction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
systemio  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowtext      = "default"
base            = "base"
alternatebase   = "#2a364d"
text            = "default"
tooltipbase     = "#ffefbb"
tooltiptext     = "base"
button          = "#161f31"
buttontext      = "default"
brighttext      = "base"
highlight       = "#455d8a"
highlightedtext = "default"
link            = "blue"
linkvisited     = "blue"
accent          = "#455d8a"

[GUI]
helpText   = "default:192"
fadedText  = "faded"
errorText  = "red"

[Syntax]
background     = "#141925"
text           = "#7d93a1"
line           = "#1b1c22"
link           = "blue"
headertext     = "#ffefbb"
headertag      = "#ffefbb80"
emphasis       = "yellow"
whitespace     = "blue:32"
dialog         = "default"
altdialog      = "purple"
note           = "red"
hidden         = "faded"
shortcode      = "green"
keyword        = "green"
tag            = "blue"
value          = "blue"
optional       = "faded"
spellcheckline = "red"
errorline      = "cyan"
replacetag     = "blue"
modifier       = "green"
texthighlight  = "faded:80"
