[Main]
name       = (private) TKSC
mode       = dark
author     = Myian

[Base]
base    = #191f2c
default = #cdd9e4
faded   = #56687c
red     = #ff8383
orange  = #e7a172
yellow  = #ebcd97
green   = #87cc97
cyan    = #6acfc7
blue    = #95cdf3
purple  = #bc90d6

[Project]
root     = default
folder   = yellow
file     = default
title    = red
chapter  = #548d60
scene    = green
note     = faded
active   = default
inactive = faded
disabled = #2b374e

[Icon]
tool      = default
sidebar   = default
accept    = green
reject    = red
action    = default
altaction = orange
apply     = green
create    = yellow
destroy   = faded
reset     = green
add       = green
change    = green
remove    = red
shortcode = green
markdown  = default
systemio  = yellow
info      = blue
warning   = orange
error     = red

[Palette]
window          = base
windowtext      = default
base            = base
alternatebase   = #2a364d
text            = default
tooltipbase     = yellow
tooltiptext     = base
button          = #161f31
buttontext      = default
brighttext      = base
highlight       = yellow
highlightedtext = base
link            = blue
linkvisited     = blue
accent          = yellow

[GUI]
helptext  = #8297ad
fadedtext = faded
errortext = red

[Syntax]
background     = #141925
text           = default
line           = #1d2636
link           = blue
headertext     = #ffffff
headertag      = faded
emphasis       = yellow
whitespace     = blue:72
dialog         = red
altdialog      = purple
note           = green
hidden         = faded
shortcode      = #548d60
keyword        = #5687be
tag            = blue
value          = #ffffff
optional       = cyan
spellcheckline = red
errorline      = green
replacetag     = #5687be
modifier       = #548d60
texthighlight  = #2a364d