[Main]
name   = Eclipse
mode   = dark
author = Myian

[Base]
base    = #212a3d
default = #e6eaf1
faded   = #a8b2c7
red     = #fa8ea0
orange  = #e2ac97
yellow  = #f5e4c0
green   = #8ae99a
cyan    = #a5e6d0
blue    = #7aacdb
purple  = #c197f0

[Project]
root     = default
folder   = orange
file     = default
title    = red
chapter  = green
scene    = blue
note     = yellow
active   = cyan
inactive = orange
disabled = #95a0b6

[Icon]
tool      = default
sidebar   = default
accept    = green
reject    = red
action    = default
altaction = orange
apply     = green
create    = yellow
destroy   = faded
reset     = green
add       = green
change    = green
remove    = red
shortcode = #e6acd8
markdown  = default
systemio  = yellow
info      = blue
warning   = orange
error     = red

[Palette]
window          = #171f30
windowtext      = default
base            = #171f30
alternatebase   = #2f3950
text            = default
tooltipbase     = yellow
tooltiptext     = base:D175
button          = base
buttontext      = default
brighttext      = base
highlight       = #e2cea2
highlightedtext = base:D175
link            = red
linkvisited     = red
accent          = #ce9ac3

[GUI]
helptext  = faded
fadedtext = faded
errortext = red

[Syntax]
background     = base
text           = default
line           = #21202e
link           = orange
headertext     = blue
headertag      = blue:128
emphasis       = blue
whitespace     = purple:100
dialog         = green
altdialog      = orange
note           = yellow
hidden         = faded
shortcode      = #e6acd8
keyword        = red
tag            = yellow
value          = faded
optional       = faded
spellcheckline = red
errorline      = green
replacetag     = yellow
modifier       = purple
texthighlight  = #717a8d
