[Main]
name   = "Friendly Spring"
mode   = "light"
author = "Myian"

[Base]
base    = "#f8e7eb"
default = "#7c7588"
faded   = "#b3a5ae"
red     = "#e68191"
orange  = "#dd996c"
yellow  = "#d3b75b"
green   = "#48a345"
cyan    = "#43b4b8"
blue    = "#6299ca"
purple  = "#bb6dae"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "green"
inactive = "faded"
disabled = "#cec1c7"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "yellow"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "orange"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "yellow"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#fad2dc"
text            = "default"
tooltipBase     = "#ffecad"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#ffbfce"
highlightedText = "default:D130"
link            = "blue"
linkVisited     = "blue"
accent          = "#eecfa9"

[GUI]
helpText     = "faded:D125"
fadedText    = "faded"
errorText    = "red"
accentText   = "red"
activeButton = "red:96"
activeBase   = "#fdf5f7"
searchMatch  = "orange:80"

[Syntax]
background     = "#fdf5f7"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "red"
headerTag      = "red:128"
emphasis       = "blue"
whitespace     = "red:80"
dialog         = "green"
altDialog      = "purple"
note           = "orange"
hidden         = "faded"
shortcode      = "orange"
keyword        = "#ce5c58"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "purple"
modifier       = "#b46e4d"
textHighlight  = "red:64"
