[Main]
name   = "Friendly Summer"
mode   = "light"
author = "Myian"

[Base]
base    = "#f0f3e9"
default = "#6c747a"
faded   = "#9caaad"
red     = "#ee7a8d"
orange  = "#dd8c6c"
yellow  = "#caa24a"
green   = "#65a857"
cyan    = "#43b4b8"
blue    = "#6299ca"
purple  = "#b779bd"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "green"
inactive = "faded"
disabled = "#b5caca"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "yellow"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "blue"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "yellow"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#d0ebc3"
text            = "default"
tooltipBase     = "#ffecad"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#b6e2a0"
highlightedText = "default:D120"
link            = "blue"
linkVisited     = "blue"
accent          = "#81c274"

[GUI]
helpText     = "faded:D125"
fadedText    = "faded"
errorText    = "red"
accentText   = "green"
activeButton = "green:64"
activeBase   = "#f9fdf7"
searchMatch  = "blue:80"

[Syntax]
background     = "#fbfdf7"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "green"
headerTag      = "green:128"
emphasis       = "#c5965d"
whitespace     = "green:64"
dialog         = "green"
altDialog      = "purple"
note           = "blue"
hidden         = "faded"
shortcode      = "blue"
keyword        = "#c04d5c"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "purple"
modifier       = "#466aa1"
textHighlight  = "green:64"
