[Main]
name   = "Lovely Winter"
mode   = "light"
author = "Myian"

[Base]
base    = "#e5eff3"
default = "#6c6f83"
faded   = "#a3aab3"
red     = "#da8b95"
orange  = "#d69c86"
yellow  = "#bea550"
green   = "#6e9e80"
cyan    = "#67c5bd"
blue    = "#639eb9"
purple  = "#ca81be"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "blue"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "yellow"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "purple"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "yellow"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#cbe7ee"
text            = "default"
tooltipBase     = "#ffecad"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#bae6f1"
highlightedText = "default:D125"
link            = "blue"
linkVisited     = "blue"
accent          = "#eecfa9"

[GUI]
helpText     = "faded:D125"
fadedText    = "faded"
errorText    = "red"
accentText   = "blue"
activeButton = "blue:64"
activeBase   = "#f7fbfd"
searchMatch  = "green:80"

[Syntax]
background     = "#f7fbfd"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "#63acb9"
headerTag      = "#63acb980"
emphasis       = "blue"
whitespace     = "red:80"
dialog         = "green"
altDialog      = "orange"
note           = "purple"
hidden         = "faded"
shortcode      = "purple"
keyword        = "#bb5a67"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "orange"
modifier       = "#92609e"
textHighlight  = "blue:64"
